name: 'Setup'
description: 'Setup npm'

runs:
  using: 'composite'
  steps:
    - name: Setup Node v16.x
      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
      with:
        node-version: 16.x

    - name: Cache node_modules # Loads cached node_modules, otherwise caches them on job completion
      id: cache
      uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
      with:
        path: |
          node_modules
          packages/**/node_modules
        key: cache-node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      run: npm ci
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'