GITHUB_REF="release-package-alpha_0.0.2"
VERSION=$(echo "${GITHUB_REF}" | cut -d "_" -f2)
SEMVER="${VERSION%%-*}"
VERSION_SUFFIX="${VERSION#*-}"
VERSION_TAG_NAME="${VERSION_SUFFIX%%.*}"
VERSION_TAG_NUMBER="${VERSION_SUFFIX#*.}"

if [[ "$VERSION_SUFFIX" == "$VERSION" ]]; then
  VERSION_SUFFIX=""
  VERSION_TAG_NAME=""
  VERSION_TAG_NUMBER=""
fi
