name: 'Publish npm package'

inputs:
  registry:
    description: 'Target registry (e.g. registry.npmjs.org)'
    required: true
    type: string
  scope:
    description: 'Package scope'
    required: true
    type: string
  name:
    description: 'Package name (without scope)'
    required: true
    type: string
  dry-run:
    description: 'Toggle for --dry-run flag'
    required: true
    type: string
  NPM_FETCH_TOKEN:
    description: 'Token used to fetch NPM packages'
    required: true
    type: string
  NPM_TAG:
    description: 'The NPM tag to be used for the released version'
    required: false
    type: string
  PACKAGE_PUBLISH_TOKEN:
    description: 'Token used to publish the package to the selected registry'
    required: false
    type: string
  version:
    description: 'The version to be released'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: checkout branch
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      with:
        fetch-depth: 0
    - name: Update package.json
      uses: jaywcjlove/github-action-package@49a5421db5e6491fef68091038ab6f3516755154
      with:
        path: "${{ inputs.name }}/package.json"
        rename: "${{ inputs.scope }}/${{ inputs.name }}"
        version: "${{ inputs.version }}"
    - run: npm config set scope ${{ inputs.scope }}
      shell: bash
    - run: npm config set ${{ inputs.scope }}:registry 'https://${{ inputs.registry }}/'
      shell: bash
    - run: npm config set //${{ inputs.registry }}/:_authToken ${{ inputs.PACKAGE_PUBLISH_TOKEN }}
      shell: bash
    - run: npm config set //${{ inputs.registry }}/:always-auth true
      shell: bash
    - name: Publish package to https://${{ inputs.registry }}
      shell: bash
      run: |
        cd "${{ inputs.name }}"
        if [ -n "${{ inputs.NPM_TAG }}" ] && [ ! "${{ inputs.dry-run }}" ]; then
          echo "NPM tag is not set. Skipping tag creation."
          npm publish --no-git-checks ${{ inputs.dry-run == 'true' && '--dry-run' || '' }}
          exit 0
        fi
        npm publish --no-git-checks --tag "${{ inputs.NPM_TAG }}"
      env:
        NODE_AUTH_TOKEN: ${{ inputs.PACKAGE_PUBLISH_TOKEN }}