name: Release Workflow

on:
  workflow_call:
    inputs:
      LABEL_NAME:
        description: 'The PR Github label name required for the release'
        required: true
        type: string
      PACKAGEJSON_DIR:
        description: 'The directory of the package to be released'
        required: true
        type: string
      TAG_PREFIX:
        description: 'The prefix of the tag to be applied'
        required: true
        type: string
      PACKAGE_NAME:
        description: 'The name of the package to be released'
        required: true
        type: string
      ENV_TAG:
        description: 'The name of the environment to be released'
        required: true
        type: string
      SCOPE:
        description: 'The scope that the package is getting published with'
        required: true
        type: string
      REGISTRY:
        description: 'The target registry'
        required: true
        type: string
      DRY_RUN:
        description: 'Flag for publishing with --dry-run'
        required: true
        type: boolean

jobs:
  version:
    runs-on: ubuntu-latest
    env:
      GITHUB_REF: ${{ github.head_ref }}
    outputs:
      RELEASE_VERSION: ${{ steps.set-version.outputs.version }}
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/setup
    - name: Set Version
      id: set-version
      # VERSION=$(echo "${{ env.GITHUB_REF }}" | rev | cut -d "_" -f 1 | rev)
      run: |
        VERSION=$(node ./node_modules/.bin/semver -c "${{ env.GITHUB_REF }}")
        echo "VERSION=${VERSION}" >> "$GITHUB_OUTPUT"
        echo "Version to be released: ${VERSION}"