name: Release Label A

on:
  pull_request:
    types: [ labeled ]
    branches:
      - 'main'
      - 'release*'
      - 'hotfix*'
jobs:
  release-workflow:
    if: ${{ github.event.label.name == 'release-label-a' }}
    uses: ./.github/workflows/release-workflow.yml
    permissions:
      contents: write
    secrets: inherit
    with:
      LABEL_NAME: 'release-label-a'
      PACKAGEJSON_DIR: 'sonny-test-package-alpha'
      TAG_PREFIX: 'v'
      PACKAGE_NAME: 'sonny-test-package-alpha'
      ENV_TAG: 'release'
      SCOPE: '@andreasonny83'
      REGISTRY: 'npm.pkg.github.com'
      DRY_RUN: false
