name: Release Workflow

on:
  workflow_call:
    inputs:
      LABEL_NAME:
        description: 'The PR Github label name required for the release'
        required: true
        type: string
      PACKAGEJSON_DIR:
        description: 'The directory of the package to be released'
        required: true
        type: string
      TAG_PREFIX:
        description: 'The prefix of the tag to be applied'
        required: true
        type: string
      PACKAGE_NAME:
        description: 'The name of the package to be released'
        required: true
        type: string
      ENV_TAG:
        description: 'The name of the environment to be released'
        required: true
        type: string
      SCOPE:
        description: 'The scope that the package is getting published with'
        required: true
        type: string
      REGISTRY:
        description: 'The target registry'
        required: true
        type: string
      DRY_RUN:
        description: 'Flag for publishing with --dry-run'
        required: true
        type: boolean

jobs:
  version:
    runs-on: ubuntu-latest
    env:
      GITHUB_REF: ${{ github.head_ref }}
    outputs:
      RELEASE_VERSION: ${{ steps.set-version.outputs.version }}
      RELEASE_SEMVER: ${{ steps.set-version.outputs.semver }}
      RELEASE_TAG: ${{ steps.set-version.outputs.versionTagName }}
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      with:
        fetch-depth: 0
    - name: Set Version
      id: set-version
      run: |
        VERSION=$(echo "${{ env.GITHUB_REF }}" | cut -d "_" -f2)
        SEMVER="${VERSION%%-*}"
        VERSION_SUFFIX="${VERSION#*-}"
        VERSION_TAG_NAME="${VERSION_SUFFIX%%.*}"
        echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
        echo "semver=${SEMVER}" >> "$GITHUB_OUTPUT"
        echo "versionTagName=${VERSION_TAG_NAME}" >> "$GITHUB_OUTPUT"
        echo "Version to be released: ${VERSION}"
        echo "Semver version: ${SEMVER}"
        echo "Version Tag Name: ${VERSION_TAG_NAME}"

  release:
    name: Bump version and release
    runs-on: ubuntu-latest
    needs: [version]
    env:
      VERSION: "${{ needs.version.outputs.RELEASE_VERSION }}"
      SEMVER: "${{ needs.version.outputs.RELEASE_SEMVER }}"
      VERSION_TAG: "${{ needs.version.outputs.RELEASE_TAG }}"
      GITHUB_REF: ${{ github.head_ref }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout branch
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          ref: ${{ env.GITHUB_REF }}
          fetch-depth: 0
          persist-credentials: false
      - name: Install npm dependencies
        uses: ./.github/actions/setup
      - name: Bump version number
        uses: jaywcjlove/github-action-package@49a5421db5e6491fef68091038ab6f3516755154
        with:
          path: "${{ inputs.PACKAGE_NAME }}/package.json"
          version: "${{ env.VERSION }}"
      - name: Commit version bump and version tag
        run: |
          git status
          echo "Tagging with: ${{ env.VERSION }}"
          git config --global user.email "andreasonny83@gmail.com"
          git config --global user.name "Github Actions Bot"
          git add "${{ inputs.PACKAGE_NAME }}/package.json"
          git tag -a "${{ inputs.TAG_PREFIX }}${{ env.VERSION }}" -m "${{ inputs.PACKAGE_NAME }} v${{ env.VERSION }}"
          git commit -m "Bump ${{ inputs.PACKAGE_NAME }} version to ${{ env.VERSION }}"
      - name: Publish package
        uses: ./.github/actions/publish
        with:
          registry: ${{ inputs.REGISTRY }}
          scope: ${{ inputs.SCOPE }}
          name: ${{ inputs.PACKAGE_NAME }}
          dry-run: ${{ inputs.DRY_RUN }}
          NPM_FETCH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_PUBLISH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}