name: Remove GitHub Label

on:
  pull_request:
    types: [labeled]

jobs:
  remove-labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    name: Remove PR labels
    steps:
      - name: Delete Label
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            return github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: context.payload.label.name
            });
